_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: certificates.yaml,horizontal-pod-autoscalers.yaml,ingress-classes.yaml
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: internal
  app.kubernetes.io/name: nginx-ingress
name: nginx-internal
namespace: nginx-internal
pvc: false
reloader: false
resources:
  - configmaps.yaml
  - deployments.yaml
  - namespaces.yaml
  - rbac.yaml
  - service-accounts.yaml
  - services.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/kubernetes/ingress-nginx
url: https://github.com/charlesthomas/homelab-nginx-internal
