_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: certificates.yaml
backups: false
helm: true
helmCrds: false
helmName: nginx-ingress
helmRelease: nginx-internal
helmRepo: https://helm.nginx.com/stable
helmValues: helm/values.yaml
helmVersion: 1.0.2
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: internal
  app.kubernetes.io/name: nginx-ingress
name: nginx-internal
namespace: nginx-internal
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://nginx.org/en/
url: https://github.com/charlesthomas/homelab-nginx-internal
