---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-internal

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-nginx-internal
commonLabels:
  app.kubernetes.io/instance: internal
  app.kubernetes.io/name: nginx-ingress

resources:
- resources/certificates.yaml
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/ingress-classes.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
- resources/services.yaml
