---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt.house
  namespace: nginx-internal
spec:
  secretName: crt.house
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "*.crt.house"
  dnsNames:
    - "*.crt.house"
