controller:
  name: controller
  kind: deployment

  # 0 to 3 ?
  logLevel: 2

  image:
    repository: nginx/nginx-ingress
    pullPolicy: IfNotPresent
    # tag: "3.3.2"

  defaultTLS:
    secret: "nginx-external/crt.house"

  wildcardTLS:
    secret: "nginx-external/crt.house"

  replicaCount: 2

  ingressClass:
    name: nginx-internal
    create: true
    setAsDefaultIngress: true

  nginxStatus:
    enable: true
    port: 8080
    allowCidrs: "127.0.0.1"

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: internal
      metallb.universe.tf/loadBalancerIPs: 192.168.1.41

    httpPort:
      enable: true
      port: 80

    httpsPort:
      enable: true
      port: 443
